from .fcn import FCN8
from .unet import UNet
from .pspn import PSPNet
from .segnet import SegNet
from .segnet import SegResNet
from .enet import ENet
from .gcn import GCN
from .deeplabv3_plus import DeepLab
from .duc_hdc import DeepLab_DUC_HDC
from .upernet import UperNet